### ISSUE TITLE
Unable to generate QueryDSL classes from JPA entities

### ISSUE THREAD

**Issue by x80486** [ryarnyah/querydsl-gradle-plugin#1]
## Describe the Bug

I have a Spring Boot project using Kotlin DSL. I'm importing this plugin like `id("com.github.ryarnyah.querydsl").version("0.0.2")`, and configuring the JPA task as:

```kotlin
tasks {
  withType<JPAExporterTask> {
    packages = arrayOf("com.pkg.domain")
  }
}
```

I do also have a JPA entity located at `com.pkg.domain`, but whenever I run the `queryDslJpaExport` I don't see anything being generated:

```shell
> Task :clean

> Task :queryDslJpaExport
given scan urls are empty. set urls in the configuration
```

## To Reproduce

Steps or Code to reproduce the behavior:
1. Configure a Kotlin DSL Gradle script with the QueryDSL plugin
1. Design a JPA entity class
1. Configure the plugin to lookup the location where the JPA class was defined
1. Trigger the `queryDslJpaExport` task

## Expected behavior

QueryDSL classes should be generated based on the JPA model at a specific location.

## Project environment (please complete the following information):
 - OS: Arch Linux `Linux uplink 5.10.19-1-lts #1 SMP Fri, 26 Feb 2021 11:11:40 +0000 x86_64 GNU/Linux`
 - Kotlin / Java Version: `1.4.30` / `Corretto-11.0.9.12.1 (build 11.0.9.1+12-LTS)`

**Comment by ryarnyah** [comment]
Thank you for your issue, i will check this ASAP (maybe today)

It's working with 0.0.3:
```
./gradlew clean compileJava queryDslJpaExport
```

**Comment by ryarnyah** [comment]
If you need it, you can use directly annotation processor like here (kotlin/kapt example):
```kotlin
dependencies {
        ...
	kapt("com.querydsl:querydsl-apt:4.4.0")
        ...
}
...
kapt {
	annotationProcessor("com.querydsl.apt.jpa.JPAAnnotationProcessor")
	javacOptions {
		option("querydsl.entityAccessors", "true")
		option("querydsl.useFields", "false")
	}
}
```

When using only Java you can do
```groovy
dependencies {
	annotationProcessor "com.querydsl:querydsl-apt:4.4.0"
	annotationProcessor 'jakarta.annotation:jakarta.annotation-api:1.3.5'
...
}
tasks.withType(JavaCompile) {
	options.compilerArgs.add("-proc:only")
	options.compilerArgs.add("-processor")
	options.compilerArgs.add("com.querydsl.apt.jpa.JPAAnnotationProcessor")
}
```

See http://www.querydsl.com/static/querydsl/4.2.1/reference/html/ch03s03.html for more options

**Comment by x80486** [comment]
Thanks for the update...that was quick! 🍹
